export const mainStats = [
  {
    value: "95%",
    description: "Read Online Reviews Before Making a Purchase",
    subtitle: "Reviews significantly influence purchasing decisions.",
    source: "Source: Status Labs, 2024",
    icon: <RateReview />,
  },
  {
    value: "98%",
    description: "Read Reviews About Local Businesses",
    subtitle: "Nearly everyone checks reviews for local services.",
    source: "Source: Status Labs, 2024",
    icon: <Info />,
  },
  {
    value: "90%+",
    description: "Influenced by Positive Reviews",
    subtitle: "Positive feedback increases the likelihood of patronage.",
    source: "Source: Status Labs, 2024",
    icon: <ThumbUp />,
  },
  {
    value: "86%",
    description: "Trust Online Reviews as Much as Personal Recommendations",
    subtitle: "Online reviews hold significant weight in consumer trust.",
    source: "Source: Status Labs, 2024",
    icon: <Star />,
  },
  {
    value: "4%",
    description: "Have Never Left a Review",
    subtitle: "The majority of consumers actively share their experiences.",
    source: "Source: Status Labs, 2024",
    icon: <Comment />,
  },
  {
    value: "80%+",
    description: "Likely to Leave Positive Review if Business Exceeds Expectations",
    subtitle: "Exceptional service encourages positive feedback.",
    source: "Source: Status Labs, 2024",
    icon: <ThumbUp />,
  },
  {
    value: "80%+",
    description: "Will Leave Positive Review if Negative Experience is Resolved",
    subtitle: "Effective issue resolution can turn critics into advocates.",
    source: "Source: Status Labs, 2024",
    icon: <Feedback />,
  },
  {
    value: "75%",
    description: "Of Online Reviews Are Left on Google",
    subtitle: "Google dominates the review platform landscape.",
    source: "Source: Status Labs, 2024",
    icon: <Google />,
  },
  {
    value: "<50%",
    description: "Frequent Businesses with Ratings Under 4 Stars",
    subtitle: "High ratings are crucial for attracting customers.",
    source: "Source: Status Labs, 2024",
    icon: <Warning />,
  },
  {
    value: "87%",
    description: "Would Not Consider Business with Rating Below 3 Stars",
    subtitle: "Low ratings can deter potential customers.",
    source: "Source: Status Labs, 2024",
    icon: <Block />,
  },
  {
    value: "90%",
    description: "More Likely to Frequent Businesses That Respond to All Reviews",
    subtitle: "Active engagement with reviews enhances customer trust.",
    source: "Source: Status Labs, 2024",
    icon: <Visibility />,
  },
];